version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform --version

  build:
    commands:
      - echo Terraform Init
      - terraform init

      - echo Terraform Validate
      - terraform validate

      - echo Terraform Plan
      - terraform plan

      - echo Terraform Apply
      - terraform apply -auto-approve